name: Skyblock
version: '1.0-SNAPSHOT'
main: me.skyblock.Skyblock
api-version: 1.17

commands:
  'eco':
    description: Economy command for admins
  'menu':
    description: Skyblock Menu Command
  'test':
    description: Test command
  'nbt':
      description: NBT test command